version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "10000:10000"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    # hostname: mysql_db
    volumes:
      - mysqldata:/var/lib/mysql
      - ./database_design/shopapp.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopee
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

volumes:
  mysqldata:
